# Generated by Django 5.0.3 on 2024-05-04 09:05

import diagnosis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='images/diagnosis_picture/default_question_picture.jpg', upload_to=diagnosis.models.DiagnosisPicture.get_upload_to)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
